//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Povestka_
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupsToSections
    {
        public int ID { get; set; }
        public string SectionNumber { get; set; }
        public string GroupNumber { get; set; }
    
        public virtual Group_ Group_ { get; set; }
        public virtual Section Section { get; set; }
    }
}
