//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Povestka_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kid()
        {
            this.KidToNewGroup = new HashSet<KidToNewGroup>();
        }
    
        public string FullName { get; set; }
        public int Age { get; set; }
        public string SchoolNumber { get; set; }
        public string Class { get; set; }
        public string BirthCertificate { get; set; }
        public string Address_ { get; set; }
        public string HomeNumber { get; set; }
        public string ParentsInfo { get; set; }
        public string CurrentGroup { get; set; }
        public System.DateTime StartDateOfTheVisit { get; set; }
    
        public virtual Group_ Group_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KidToNewGroup> KidToNewGroup { get; set; }
    }
}
