//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Povestka_
{
    using System;
    using System.Collections.Generic;
    
    public partial class KidToNewGroup
    {
        public int ID { get; set; }
        public string KidFullName { get; set; }
        public string CurrentGroup { get; set; }
        public string FutureGroup { get; set; }
        public System.DateTime StartDateOfTheVisit { get; set; }
        public System.DateTime EndDateOfTheVisit { get; set; }
    
        public virtual Kid Kid { get; set; }
    }
}
